title: PRSG Lab
description: Photogrammetry, Remote Sensing and Geoinformatics Lab at Jeonbuk National University
logo: /assets/images/jbnu-logo.png
baseurl: ""
url: ""
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
