title: PRSG Lab
description: Photogrammetry, Remote Sensing and Geoinformatics Lab at Jeonbuk National University
logo: /assets/images/jbnu-logo.png
baseurl: ""
url: ""
markdown: kramdown
permalink: pretty
collections:
  news_en:
    output: true
    permalink: /news/:name/
  news_ko:
    output: true
    permalink: /ko/news/:name/
exclude:
  - README.md
  - README.ko.md
  - Gemfile
  - Gemfile.lock
